### ISSUE TITLE
Failed loading neo4j-tp3 into dbtrento/gremlin-neo4j-tp3

### ISSUE THREAD

**Issue by lucassardois** [kuzeko/graph-databases-testsuite#23]
I have followed the steps provided in the Reproduce.md file.
After multiples days of running on a virtual machine the benchmark stopped with the following critical error:
```
2021-04-20 13:26:16,238 - __main__ - INFO - (3) meta parameters: ['ITERATION', 'BFS_DEPTH', 'SID']
2021-04-20 14:29:51,258 - __main__ - INFO - [CURRENT] query: shortest-path.groovy REPEAT 2
2021-04-20 14:29:51,259 - __main__ - INFO - Query shortest-path.groovy on freebase_large.json2 using neo4j (image: dbtrento/gremlin-neo4j)
2021-04-20 14:29:51,259 - __main__ - INFO - (2) meta parameters: ['ITERATION', 'INDEX']
2021-04-21 23:52:38,587 - __main__ - INFO - [CURRENT] query: shortest-path-labelled.groovy REPEAT 2
2021-04-21 23:52:38,588 - __main__ - INFO - Query shortest-path-labelled.groovy on freebase_large.json2 using neo4j (image: dbtrento/gremlin-neo4j)
2021-04-21 23:52:38,588 - __main__ - INFO - (2) meta parameters: ['ITERATION', 'INDEX']
2021-04-22 00:08:23,752 - __main__ - INFO - [CURRENT] DB: neo4j-tp3 w/image dbtrento/gremlin-neo4j-tp3
2021-04-22 00:08:23,752 - __main__ - INFO - [CURRENT] DATASET: mico.json2
2021-04-22 00:09:18,496 - __main__ - CRITICAL - Failed loading neo4j-tp3 into dbtrento/gremlin-neo4j-tp3
```

How to fix it?

The benchmark is running on an Openstack VM on a debian with 64Go Ram, 12vCPU and 1To disk.

**Comment by kuzeko** [comment]
Hi, can you check and report the content of the relevant error log file please?

**Comment by lucassardois** [comment]
Thanks for the answer here is are the last lines found in the file `runtime/errors.log`.
```
[NOW] gremlin-neo4j  shortest-path-labelled.groovy /runtime/data/freebase_large.json2
Convert never
UIDF: freebaseid
Loading LID
Mon Jun  7 22:24:01 UTC 2021 shortest-path-labelled.groovy
[NOW] gremlin-neo4j  shortest-path-labelled.groovy /runtime/data/freebase_large.json2
Convert never
UIDF: freebaseid
Loading LID
Loading /runtime/data/mico.json2
ALREADY tinkerpop3 /runtime/data/mico.json2
groovy.lang.MissingPropertyException: No such property: Neo4jGraph for class: groovysh_evaluate
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:66)
        at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:310)
        at groovysh_evaluate.run(groovysh_evaluate:5)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
        at org.codehaus.groovy.tools.shell.Interpreter.evaluate(Interpreter.groovy:71)
        at org.codehaus.groovy.tools.shell.Groovysh.execute(Groovysh.groovy:196)
        at org.apache.tinkerpop.gremlin.console.GremlinGroovysh.super$3$execute(GremlinGroovysh.groovy)
        at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:145)
        at org.apache.tinkerpop.gremlin.console.GremlinGroovysh.execute(GremlinGroovysh.groovy:72)
        at org.apache.tinkerpop.gremlin.console.Console$_executeInShell_closure20.doCall(Console.groovy:394)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.Closure.call(Closure.java:418)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2041)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2021)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2071)
        at org.codehaus.groovy.runtime.dgm$175.doMethodInvoke(Unknown Source)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
        at org.apache.tinkerpop.gremlin.console.Console.executeInShell(Console.groovy:371)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
        at org.apache.tinkerpop.gremlin.console.Console.<init>(Console.groovy:164)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
        at org.apache.tinkerpop.gremlin.console.Console.main(Console.groovy:481)

```
