### ISSUE TITLE
V2: ShortestPathFiltered query crash

### ISSUE THREAD

**Issue by lucassardois** [kuzeko/graph-databases-testsuite#24]
On the V2 branch, after following install instructions I got the following error:
```
16:32:54| INFO     - Running benchmark: 16f59dc0-44b7-4dbe-abf2-c4072676401e
16:32:54| DEBUG    - Loading configuration from conf.toml
16:32:54| DEBUG    - Shells are running with -d
16:32:54| DEBUG    - Main benchamark loop
16:32:54| INFO     - Current dataset is tinkerpop-modern_mod.json
16:32:54| INFO     - Overriding java options: -XX:+UseG1GC -XX:MaxDirectMemorySize=512m
16:32:54| INFO     - Current database is orientdb
16:32:54| DEBUG    - Get queries execution configuration list
16:32:56| DEBUG    - Runnig with query version: vldb19-7-dirty
16:32:56| INFO     - Current query is com.graphbenchmark.queries.vldbj.NodePathLabelSearchOut
16:32:56| INFO     - Current mode is SINGLE_SHOT
16:32:56| DEBUG    - []
16:32:56| INFO     - Current mode is BATCH
16:33:15| INFO     - Current mode is CONCURRENT
16:33:17| INFO     - Current mode is SINGLE_SHOT
16:33:17| DEBUG    - []
16:33:17| INFO     - Current mode is BATCH
16:33:35| INFO     - Current mode is CONCURRENT
16:33:37| INFO     - Current mode is SINGLE_SHOT
16:33:37| DEBUG    - []
16:33:37| INFO     - Current mode is BATCH
16:33:56| INFO     - Current mode is CONCURRENT
16:33:58| INFO     - Current query is com.graphbenchmark.queries.vldbj.NodeLabelledPropertySearch
16:33:58| INFO     - Current mode is SINGLE_SHOT
16:33:58| DEBUG    - []
16:33:58| INFO     - Current mode is BATCH
16:34:16| INFO     - Current mode is CONCURRENT
16:34:18| INFO     - Current mode is SINGLE_SHOT
16:34:18| DEBUG    - []
16:34:18| INFO     - Current mode is BATCH
16:34:36| INFO     - Current mode is CONCURRENT
16:34:38| INFO     - Current mode is SINGLE_SHOT
16:34:38| DEBUG    - []
16:34:38| INFO     - Current mode is BATCH
16:34:57| INFO     - Current mode is CONCURRENT
16:34:59| INFO     - Current query is com.graphbenchmark.queries.vldb.NodePropertySearch
16:34:59| INFO     - Current mode is SINGLE_SHOT
16:34:59| DEBUG    - [{}]
16:35:18| INFO     - Current mode is BATCH
16:35:18| INFO     - Skipping query com.graphbenchmark.queries.vldb.NodePropertySearch. It cannot be executed in BATCH mode.
16:35:18| INFO     - Current mode is CONCURRENT
16:35:37| INFO     - Current mode is SINGLE_SHOT
16:35:37| DEBUG    - [{}]
16:35:55| INFO     - Current mode is BATCH
16:35:55| INFO     - Skipping query com.graphbenchmark.queries.vldb.NodePropertySearch. It cannot be executed in BATCH mode.
16:35:55| INFO     - Current mode is CONCURRENT
16:36:14| INFO     - Current mode is SINGLE_SHOT
16:36:14| DEBUG    - [{}]
16:36:33| INFO     - Current mode is BATCH
16:36:33| INFO     - Skipping query com.graphbenchmark.queries.vldb.NodePropertySearch. It cannot be executed in BATCH mode.
16:36:33| INFO     - Current mode is CONCURRENT
16:36:51| INFO     - Current query is com.graphbenchmark.queries.vldb.KDegreeOut
16:36:51| INFO     - Current mode is SINGLE_SHOT
16:36:51| DEBUG    - [{}]
16:37:10| INFO     - Current mode is BATCH
16:37:10| INFO     - Skipping query com.graphbenchmark.queries.vldb.KDegreeOut. It cannot be executed in BATCH mode.
16:37:10| INFO     - Current mode is CONCURRENT
16:37:29| INFO     - Current mode is SINGLE_SHOT
16:37:29| DEBUG    - [{}]
16:37:48| INFO     - Current mode is BATCH
16:37:48| INFO     - Skipping query com.graphbenchmark.queries.vldb.KDegreeOut. It cannot be executed in BATCH mode.
16:37:48| INFO     - Current mode is CONCURRENT
16:38:06| INFO     - Current mode is SINGLE_SHOT
16:38:06| DEBUG    - [{}]
16:38:25| INFO     - Current mode is BATCH
16:38:25| INFO     - Skipping query com.graphbenchmark.queries.vldb.KDegreeOut. It cannot be executed in BATCH mode.
16:38:25| INFO     - Current mode is CONCURRENT
16:38:44| INFO     - Current query is com.graphbenchmark.queries.vldb.ShortestPathFiltered
16:38:44| INFO     - Current mode is SINGLE_SHOT
16:38:44| DEBUG    - [{'destination': 1, 'source': 0}, {'destination': 2, 'source': 1}, {'destination': 0, 'source': 2}]
16:39:05| ERROR    - Error in query. Code: 1
16:39:05| CRITICAL - Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 337 path $.cmd_id
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at com.google.gson.Gson.fromJson(Gson.java:846)
        at com.google.gson.Gson.fromJson(Gson.java:817)
        at com.graphbenchmark.common.GenericShell.main(GenericShell.java:269)
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 337 path $.cmd_id
        at com.google.gson.stream.JsonReader.nextString(JsonReader.java:826)
        at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
        at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        ... 5 more

16:39:05| CRITICAL - Irrecoverable error
```

Any idea on how to fix this issue?

**Comment by lucassardois** [comment]
Bump, I need to fix this issue ASAP.
Note: I have set the sampling paths property to 0, else I got this error:
```
14:18:19| INFO     - Running benchmark: 99685ee4-6993-47f8-b827-cb66f6d4aa44
14:18:19| DEBUG    - Loading configuration from conf.toml
14:18:19| DEBUG    - Shells are running with -d
14:18:19| DEBUG    - Main benchamark loop
14:18:19| INFO     - Current dataset is tinkerpop-modern_mod.json
14:18:19| INFO     - Overriding java options: -XX:+UseG1GC -XX:MaxDirectMemorySize=512m
14:18:19| INFO     - Current database is orientdb
14:18:19| CRITICAL - Config not compatible with sample file. Suggested "sampling" conf:
14:18:19| CRITICAL - {"nodes": 3, "node_labels": 2, "node_props": 3, "edges": 3, "edge_labels": 2, "edge_props": 0, "paths": 0}     
```

So this may be related? Edit: tested with Neo4J and got the same crash log as above, so this is not related to OrientDB.

**Comment by kuzeko** [comment]
Thanks for reporting.
We will try to look into it.
But with path to 0 it shortest path should not work properly

**Comment by MartinBrugnara** [comment]
Thanks for the report @lucassardois;

**JsonSyntaxException**
I see the repository is not in a clean state, did you modify `control.py` to skip the checks on the sample? did you modify the config file after creating the sample?

**Config not compatible with sample file.**
About the second, maybe, but unlikely. This error message is about a compatibility issue between the sampled data and the test configuration, _e.g._ the config calls for 10 random nodes' labels but the sample file contains only 2. This usually happens for one of these two reasons:
- when the config file (`conf.toml`) is modified after the sampling occurred, and the number of required sampled items has been increased.
- when the sampler was unable to find the requested number of items, _e.g._ when the config calls for 10 node labels but the dataset only offers 4.

To fix this second issue, either update config.toml with the values suggested by the script (or smaller), or change the `sample_id` in the config file and re-run the sampler.

**Comment by lucassardois** [comment]
Hello, the only change I made to `control.py` is the following:
```bash
diff --git a/CONTROL/control.py b/CONTROL/control.py
index c6bd436..21e5b80 100644
--- a/CONTROL/control.py
+++ b/CONTROL/control.py
@@ -552,7 +552,7 @@ def run_benchmark(config, runtime_dir, shell_dir, results, data_suffix, commit_s
                                     *BASE_ARGS,
                                 ]
                                 CMD_ID += 1
-                                run_conf['cmd_id'] = CMD_ID,
+                                run_conf['cmd_id'] = str(CMD_ID)
 
                                 cnt = client.containers.run(data_image,
                                                             args,
```

It was necessary to avoid raising error somewhere when running queries in the java part, but I don't recall where exactly...
For the others points, I tried re-sampling but this still seems strange to me. Also, how does this works when I have multiples datasets some of which with 10 nodes and others with 10 millions nodes?

**Comment by MartinBrugnara** [comment]
* `cmd_id` may be related to [this](https://github.com/kuzeko/graph-databases-testsuite/blob/133116cbcc1c61cf088441e1b5907c4fbd4531f1/SHELLS/common/src/main/java/com/graphbenchmark/common/RunConf.java#L21) but GSON should have taken care of that. Anyhow, this is not what is breaking the experiments otherwise none of the above queries would have worked and some did (`e.g. NodePathLabelSearchOut`).

If this is indeed a problem you may want to fix it also [here](https://github.com/kuzeko/graph-databases-testsuite/blob/133116cbcc1c61cf088441e1b5907c4fbd4531f1/CONTROL/control.py#L546) and [here](https://github.com/kuzeko/graph-databases-testsuite/blob/133116cbcc1c61cf088441e1b5907c4fbd4531f1/CONTROL/control.py#L566)


* "10 nodes and others with 10 millions nodes"
  1) In the config file you specify how many samples you want, _e.g._ 5 vertex labels. 
  2) During sampling the system tries to sample 5 different labels.
       In the remote case where 5 are not available, _e.g._ the datasets has only 2, then only 2 are sampled and the settings must be updated with `vertex labels = 2`. 
  3) During execution `control.py` provides the parameters to test with. _I.e._, a query based on vertex labels will be invoked 5 (or 2) times, each time with a different "vertex label".  You can see which instances are being tested from the `debug log` above (produced by [this](https://github.com/kuzeko/graph-databases-testsuite/blob/133116cbcc1c61cf088441e1b5907c4fbd4531f1/CONTROL/control.py#L557)) and in the result/timing line.

* Looking again at the log you provided it looks like your dataset does not have labels nor properties on vertexes, is this correct? Otherwise there may have been some issue either in the loading phase or sampling phase.  
--> Please share also your configuration and sampling files.

**Comment by lucassardois** [comment]
* Regarding `cmd_id` GSON was raising an exception stopping the benchmark process that's why I had to fix the issue.



**My config file:**
```toml
queries = [ "com.graphbenchmark.queries.vldbj.NodePathLabelSearchOut", "com.graphbenchmark.queries.vldbj.NodeLabelledPropertySearch", "com.graphbenchmark.queries.vldb.NodePropertySearch", "com.graphbenchmark.queries.vldb.KDegreeOut", "com
.graphbenchmark.queries.vldb.ShortestPathFiltered", "com.graphbenchmark.queries.vldbj.NodeKReachability", "com.graphbenchmark.queries.vldb.BFS", "com.graphbenchmark.queries.vldb.InsertNodeProperty", "com.graphbenchmark.queries.vldb.NNinco
mingUniqueLabel", "com.graphbenchmark.queries.vldb.CountNodes", "com.graphbenchmark.queries.vldb.InsertEdgeWithProperty", "com.graphbenchmark.queries.vldb.NNbothUniqueLabel", "com.graphbenchmark.queries.vldb.IdSearchEdge", "com.graphbench
mark.queries.vldb.DeleteEdgeProperty", "com.graphbenchmark.queries.vldbj.NodePathLabelSearch", "com.graphbenchmark.queries.MixCountInsertSchema", "com.graphbenchmark.queries.vldb.EdgeLabelSearch", "com.graphbenchmark.queries.vldbj.InsertN
ode", "com.graphbenchmark.queries.vldbj.AllNodeLabelPatternSquare", "com.graphbenchmark.queries.vldbj.NodeLabelSearch", "com.graphbenchmark.queries.vldbj.Noop", "com.graphbenchmark.queries.vldb.CountEdges", "com.graphbenchmark.queries.vld
b.InsertNodeWithProperty", "com.graphbenchmark.queries.vldbj.NodeKReachabilityOut", "com.graphbenchmark.queries.vldb.KDegreeIn", "com.graphbenchmark.queries.vldb.DeleteNode", "com.graphbenchmark.queries.vldb.InsertNodeWithEdges", "com.gra
phbenchmark.queries.MixCountDelete", "com.graphbenchmark.queries.vldbj.NodeLabelledKReachability", "com.graphbenchmark.queries.vldb.UpdateNodeProperty", "com.graphbenchmark.queries.vldb.UpdateEdgeProperty", "com.graphbenchmark.queries.vld
b.BFSfiltered", "com.graphbenchmark.queries.vldb.NNincoming", "com.graphbenchmark.queries.vldbj.NodePatternTriangle", "com.graphbenchmark.queries.vldb.KDegreeBoth", "com.graphbenchmark.queries.vldbj.AllEdgeLabelPatternSquare", "com.graphb
enchmark.queries.vldbj.NodePatternSquare", "com.graphbenchmark.queries.vldb.ShortestPath", "com.graphbenchmark.queries.vldb.CountNonRoot", "com.graphbenchmark.queries.vldb.NodeUIDSearch", "com.graphbenchmark.queries.vldb.NNbothFiltered", 
"com.graphbenchmark.queries.vldbj.AllEdgeLabelPatternTriangle", "com.graphbenchmark.queries.vldb.IdSearchNode", "com.graphbenchmark.queries.vldb.DeleteNodeProperty", "com.graphbenchmark.queries.vldbj.NodeLabelledKReachabilityOut", "com.gr
aphbenchmark.queries.vldbj.CountUniqueNodeLabels", "com.graphbenchmark.queries.MixCountInsertSimple", "com.graphbenchmark.queries.vldb.NNoutgoingUniqueLabel", "com.graphbenchmark.queries.vldb.NNoutgoing", "com.graphbenchmark.queries.vldb.
InsertEdgeProperty", "com.graphbenchmark.queries.vldb.CountUniqueEdgeLabels", "com.graphbenchmark.queries.vldb.InsertEdge", "com.graphbenchmark.queries.vldb.EdgePropertySearch", "com.graphbenchmark.queries.vldbj.AllNodeLabelPatternTriangl
e",]                                                                                                                                                                                                                                          
warmup = []                                                                                                                                                                                                                                   
loader = "com.graphbenchmark.queries.mgm.Load"                                                                                                                                                                                                
sampler = "com.graphbenchmark.queries.mgm.Sampler"                                                                                                                                                                                            
mapsample = "com.graphbenchmark.queries.mgm.MapSample"                                                                                                                                                                                        
sample_id = "dbf21247-0b6b-4123-aedd-a67968a9ba8d"                                                                                                                                                                                            
modes = [ "SINGLE_SHOT",]                                                                                                                                                                                                                     
iterations = 3                                                                                                                                                                                                                                
threads = 3                                                                                                                                                                                                                                   
jvm_opts = "-XX:+UseG1GC -XX:+UnlockExperimentalVMOptions"                                                                                                                                                                                    
                                                                                                                                                                                                                                              
[sampling]                                                                                                                                                                                                                                    
nodes = 3                                                                                                                                                                                                                                     
node_labels = 2                                                                                                                                                                                                                               
node_props = 3                                                                                                                                                                                                                                
edges = 3                                                                                                                                                                                                                                     
edge_labels = 2
edge_props = 0
paths = 0
paths_max_len = 5

[timeout]
single_shot = 1800
batch = 10800
concurrent = 3600
load = 86400
extra_container = 600
consecutive = 3

[cnt_opts]
security_opt = [ "seccomp=unconfined",]
mem_limit = 267252325908
mem_swappiness = 1
cap_add = [ "IPC_LOCK",]

[databases.neo4j]
image = "graphbenchmark.com/neo4j:latest"

[databases.orientdb]
image = "graphbenchmark.com/orientdb:latest"
jvm_opts = "-XX:+UseG1GC -XX:MaxDirectMemorySize=512m"

[databases.arangodb]
image = "graphbenchmark.com/arangodb:latest"

[databases.sqlgpg]
image = "graphbenchmark.com/sqlgpg:latest"

# [databases.janusgraph]
# image = "graphbenchmark.com/janusgraph:latest"

# [datasets."tinkerpop-modern_mod.json"]
# path = "/runtime/data/tinkerpop-modern_mod.json"
# uid_field = "uid"

[datasets."air-routes.json"]
path = "/runtime/data/air-routes.json"
uid_field = "uid"

# [datasets."dbpedia.escaped.json"]
# path = "/runtime/data/dbpedia.escaped.json"
# uid_field = "uid"
#
# [datasets."ldbc.scale10.escaped.json"]
# path = "/runtime/data/ldbc.scale10.escaped.json"
# uid_field = "uid"

[cnt_opts.ulimits.memlock]
hard = -1
soft = -1
```

**Sample for tinkerpop-modern:**
```json
{"nodes":[5,2,4],"node_labels":["software","person"],"node_props":[{"label":"person","name":"uid","type":"java.lang.Long"},{"label":"software","name":"lang","type":"java.lang.String"},{"label":"person","name":"name","type":"java.lang.String"}],"edges":[{"source":1,"target":4,"label":"knows"},{"source":4,"target":3,"label":"created"},{"source":6,"target":3,"label":"created"}],"edge_labels":["knows","created"],"edge_props":[],"paths":[],"max_uid":6,"sample_id":"dbf21247-0b6b-4123-aedd-a67968a9ba8d"}
```

**Sample for air-routes:**
```json
{"nodes":[3559,3546,3555],"node_labels":["continent","airport"],"node_props":[{"label":"airport","name":"code","type":"java.lang.String"},{"label":"airport","name":"elev","type":"java.lang.Integer"},{"label":"airport","name":"type","type":"java.lang.String"}],"edges":[{"source":3737,"target":33,"label":"contains"},{"source":3506,"target":133,"label":"contains"},{"source":3692,"target":293,"label":"contains"}],"edge_labels":["contains","route"],"edge_props":[],"paths":[],"max_uid":3741,"sample_id":"dbf21247-0b6b-4123-aedd-a67968a9ba8d"}
```

**Comment by MartinBrugnara** [comment]
Though this configuration is not the one from the first logs correct? 
Otherwise it shouldn't have printed `Current mode is CONCURRENT`.
And the number of examples seams correct.

Be advised that, since you are missing some samples, some queries will essentially not run. In this specific instance, the one based on paths or edge properties are examples.

**Comment by lucassardois** [comment]
> Though this configuration is not the one from the first logs correct?
> Otherwise it shouldn't have printed `Current mode is CONCURRENT`.
> And the number of examples seams correct.

You are right, but from what I recall, this is the only thing that I changed since then. I just removed the `CONCURRENT` and `BATCH` from the modes array.

> Be advised that, since you are missing some samples, some queries will essentially not run. In this specific instance, the one based on paths or edge properties are examples.

Okay.

**Comment by MartinBrugnara** [comment]
Perfect, closing here.
Please feel free to open a new issue if you encounter further problems.

**Comment by lucassardois** [comment]
> Bump, I need to fix this issue ASAP.
> Note: I have set the sampling paths property to 0, else I got this error:
> 
> ```
> 14:18:19| INFO     - Running benchmark: 99685ee4-6993-47f8-b827-cb66f6d4aa44
> 14:18:19| DEBUG    - Loading configuration from conf.toml
> 14:18:19| DEBUG    - Shells are running with -d
> 14:18:19| DEBUG    - Main benchamark loop
> 14:18:19| INFO     - Current dataset is tinkerpop-modern_mod.json
> 14:18:19| INFO     - Overriding java options: -XX:+UseG1GC -XX:MaxDirectMemorySize=512m
> 14:18:19| INFO     - Current database is orientdb
> 14:18:19| CRITICAL - Config not compatible with sample file. Suggested "sampling" conf:
> 14:18:19| CRITICAL - {"nodes": 3, "node_labels": 2, "node_props": 3, "edges": 3, "edge_labels": 2, "edge_props": 0, "paths": 0}     
> ```
> 
> So this may be related? Edit: tested with Neo4J and got the same crash log as above, so this is not related to OrientDB.

@MartinBrugnara about this, to which value should I then set the paths key in the config file? When I don't set it to 0 (and leave it as generated by the Makefile) I'm getting critical errors. I would like to be able to run as many queries as possible.

**Comment by MartinBrugnara** [comment]
On Mon, Aug 30, 2021, at 3:15 PM, Lucas S. wrote:
> 
> 
> > Bump, I need to fix this issue ASAP.
> > Note: I have set the sampling paths property to 0, else I got this error:
> > 
> > `14:18:19| INFO     - Running benchmark: 99685ee4-6993-47f8-b827-cb66f6d4aa44
> > 14:18:19| DEBUG    - Loading configuration from conf.toml
> > 14:18:19| DEBUG    - Shells are running with -d
> > 14:18:19| DEBUG    - Main benchamark loop
> > 14:18:19| INFO     - Current dataset is tinkerpop-modern_mod.json
> > 14:18:19| INFO     - Overriding java options: -XX:+UseG1GC -XX:MaxDirectMemorySize=512m
> > 14:18:19| INFO     - Current database is orientdb
> > 14:18:19| CRITICAL - Config not compatible with sample file. Suggested "sampling" conf:
> > 14:18:19| CRITICAL - {"nodes": 3, "node_labels": 2, "node_props": 3, "edges": 3, "edge_labels": 2, "edge_props": 0, "paths": 0}     
> ` 
> > So this may be related? Edit: tested with Neo4J and got the same crash log as above, so this is not related to OrientDB.
> > 
> @MartinBrugnara <https://github.com/MartinBrugnara> about this, to 
> which value should I then set the paths key in the config file? When I 
> don't set it to 0 (and leave it as generated by the Makefile) I'm 
> getting critical errors. I would like to be able to run as many queries 
> as possible.
> 

tinkerpop-modern_mod.json is a dataset just for devel.
I would suggest to ignore that dataset, and focus on the others. I see no reason why "paths" should not be 10 or more.

Note also that once you have a "sampled" image (image committed w.r.t a samples) you can always use less samples, but not more -- this is hacky/advanced usage, but yes.


-- 
Martin Brugnara
https://martinbrugnara.it
